/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Mariano
 */
public class pnlManagement extends javax.swing.JFrame {

    /**
     * Creates new form pnlManagement
     */
    public pnlManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManagement = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlManagement.setName("pnlManagement"); // NOI18N

        tblManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblManagement);

        btnDelete.setBackground(new java.awt.Color(217, 83, 79));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(217, 148, 79));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(90, 153, 207));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManagementLayout = new javax.swing.GroupLayout(pnlManagement);
        pnlManagement.setLayout(pnlManagementLayout);
        pnlManagementLayout.setHorizontalGroup(
            pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManagementLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        pnlManagementLayout.setVerticalGroup(
            pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManagementLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        int row = tblManagement.getSelectedRow();

        if (currentData.equals("Employee")) {
            if (row != -1) {

                String strEmployeeId = tblManagement.getModel().getValueAt(row, 0).toString();
                employeeController.deleteEmployee(populatedTable, strEmployeeId);

            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }

        if (currentData.equals("Students")) {
            try {
                entityController.btnDeleteStudent(tblManagement);
                entityModel.populateTable(entityModel.fetchStudents(), populatedTable);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }
        if (currentData.equals("SubjectSchedule")) {
            if (row != -1) {
                String strSubjectCode = tblManagement.getModel().getValueAt(row, 4).toString();
                String strCollegeCode = tblManagement.getModel().getValueAt(row, 2).toString();
                String strSYear = tblManagement.getModel().getValueAt(row, 0).toString();
                String strSemester = tblManagement.getModel().getValueAt(row, 1).toString();
                String strBlockNo = tblManagement.getModel().getValueAt(row, 3).toString();
                String strSequenceNo = tblManagement.getModel().getValueAt(row, 10).toString();
                entityModel.deleteSubjectSchedule(strSubjectCode, strCollegeCode, strSequenceNo, strBlockNo, strSemester, strSYear);
                entityModel.populateTable(entityModel.fetchSubjectSchedules(), populatedTable);
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }

        if (currentData.equals("College")) {
            if (row != -1) {
                String strCollegeCode = tblManagement.getModel().getValueAt(row, 0).toString();
                String strDescription = tblManagement.getModel().getValueAt(row, 1).toString();
                String strDateOpened = tblManagement.getModel().getValueAt(row, 2).toString();
                String strDateClosed = tblManagement.getModel().getValueAt(row, 3).toString();
                String strStatus = tblManagement.getModel().getValueAt(row, 4).toString();
                entityModel.deleteCollege(strCollegeCode, strDescription, strDateOpened, strDateClosed, strStatus);
                entityModel.populateTable(entityModel.fetchColleges(), populatedTable);
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:

        boolAdd = false;
        System.out.println(currentData);
        if (currentData.equals("Students")) {
            switchToCard("pnlStudent");
            entityController.populateCourseOptions(cmbCourseCode);
            entityController.btnSetFields(
                tblManagement,
                txtStudentNo,
                txtLastNameStudent,
                txtFirstNameStudent,
                txtEmailStudent,
                cmbGenderStudent,
                cmbCourseCode,
                txtPhoneNo,
                txtAddressStudent,
                txtBirthdayStudent,
                cmbStatusStudent,
                txtDateStartedStudent,
                txtDateGraduatedStudent);
        }
        if (currentData.equals("College")) {
            int row = tblManagement.getSelectedRow();

            if (row != -1) {
                oldCollegeCode = tblManagement.getModel().getValueAt(row, 0).toString();
                oldDescription = tblManagement.getModel().getValueAt(row, 1).toString();
                oldDateOpened = tblManagement.getModel().getValueAt(row, 2).toString();
                oldDateClosed = tblManagement.getModel().getValueAt(row, 3).toString();
                oldStatus = tblManagement.getModel().getValueAt(row, 4).toString();

                txtCollegeCode1.setText(oldCollegeCode);
                txtDesc.setText(oldDescription);
                txtDateOp.setText(oldDateOpened);
                txtDateCl.setText(oldDateClosed);
                txtStatus.setSelectedItem(oldStatus);
                switchToCard("pnlAddCollege");
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }

        if (currentData.equals("SubjectSchedule")) {
            int row = tblManagement.getSelectedRow();
            populateSchedOptions();
            if (row != -1) {
                String dayCode = switch (tblManagement.getModel().getValueAt(row, 6).toString()) {
                    case "M" ->
                    "Monday";
                    case "T" ->
                    "Tuesday";
                    case "W" ->
                    "Wednesday";
                    case "Th" ->
                    "Thursday";
                    case "F" ->
                    "Friday";
                    case "S" ->
                    "Saturday";
                    case "Su" ->
                    "Sunday";
                    default ->
                    "";
                };
                String collegeCode = findItemInResultSet(entityModel.fetchColleges(), tblManagement.getModel().getValueAt(row, 2).toString(), "college_code", "description");
                switchToCard("pnlAddSubjSched");
                cmbSYear.setSelectedItem(tblManagement.getModel().getValueAt(row, 0).toString());
                cmbSemester.setSelectedItem(tblManagement.getModel().getValueAt(row, 1).toString());
                cmbCollegeCode.setSelectedItem(collegeCode);
                cmbEmployeeName.setSelectedItem(tblManagement.getModel().getValueAt(row, 12).toString());
                cmbSubjectCode.setSelectedItem(tblManagement.getModel().getValueAt(row, 5).toString());
                cmbDay.setSelectedItem(dayCode);
                txtTime.setText(tblManagement.getModel().getValueAt(row, 7).toString());
                txtRoom.setText(tblManagement.getModel().getValueAt(row, 8).toString());
                txtType.setText(tblManagement.getModel().getValueAt(row, 9).toString());
                txtSequence.setText(tblManagement.getModel().getValueAt(row, 10).toString());
                txtBlockNo.setText(tblManagement.getModel().getValueAt(row, 3).toString());
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }
        System.out.println(currentData.equals("Employee"));

        if (currentData.equals("Employee")) {
            int row = tblManagement.getSelectedRow();
            System.out.println(row);

            if (row != -1) {
                oldEmployeeID = tblManagement.getValueAt(row, 0).toString();
                oldLastName = tblManagement.getValueAt(row, 1).toString();
                oldFirstName = tblManagement.getValueAt(row, 2).toString();
                oldEmail = tblManagement.getValueAt(row, 3).toString();
                oldGender = tblManagement.getValueAt(row, 4).toString();
                oldCpNum = tblManagement.getValueAt(row, 5).toString();
                oldAddress = tblManagement.getValueAt(row, 6).toString();
                oldBirthdate = tblManagement.getValueAt(row, 7).toString();
                oldStatus = tblManagement.getValueAt(row, 8).toString();
                oldDateStarted = tblManagement.getValueAt(row, 9).toString();
                oldDateResigned = tblManagement.getValueAt(row, 10).toString();

                switchToCard("pnlAddEmployee");
                txtEmpID.setText(oldEmployeeID);
                txtLastName.setText(oldLastName);
                txtFirstName.setText(oldFirstName);
                txtEmail.setText(oldEmail);
                cmbGender.setSelectedItem(oldGender);
                txtCpNo.setText(oldCpNum);
                txtAddress.setText(oldAddress);
                txtBirthdate.setText(oldBirthdate);
                cmbEmployeeStat.setSelectedItem(oldStatus);
                txtDateStarted.setText(oldDateStarted);
                txtDateResigned.setText(oldDateResigned);
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }

        if (currentData.equals("StudentGrades")) {
            int row = tblManagement.getSelectedRow();

            if (row != -1) {

                oldSchoolYear = tblManagement.getModel().getValueAt(row, 0).toString();
                oldSemester = tblManagement.getModel().getValueAt(row, 1).toString();
                oldStudentNo = findConcatenatedItemInResultSet(entityModel.fetchStudents(), tblManagement.getModel().getValueAt(row, 2).toString(), "lastname", "firstname", "student_no");
                oldSubjectCode = findItemInResultSet(entityModel.fetchSubjects(), tblManagement.getModel().getValueAt(row, 3).toString(), "description", "subject_code");
                oldAddGradeBlockNo = tblManagement.getModel().getValueAt(row, 4).toString();
                oldGrade = Double.parseDouble(tblManagement.getModel().getValueAt(row, 5).toString());

                cmbSYear2.setSelectedItem(oldSchoolYear);
                cmbSemester2.setSelectedItem(oldSemester);
                cmbStudentName.setSelectedItem(oldStudentNo);
                cmbSubjectDesc2.setSelectedItem(oldSubjectCode);
                txtBlockNo.setText(oldAddGradeBlockNo);
                cmbGrade.setSelectedItem(oldGrade);
                switchToCard("pnlAddGrade");
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        boolAdd = true;
        System.out.println(currentData);
        if (currentData.equals("SubjectSchedule")) {
            switchToCard("pnlAddSubjSched");
            populateSchedOptions();
        }

        if (currentData.equals("College")) {
            switchToCard("pnlAddCollege");
        }

        if (currentData.equals("Students")) {
            switchToCard("pnlStudent");
            entityController.populateCourseOptions(cmbCourseCode);
        }

        if (currentData.equals("Employee")) {
            switchToCard("pnlAddEmployee");
        }

        if (currentData.equals("StudentGrades")) {
            switchToCard("pnlAddGrade");
            populateGradeOptions();
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnlManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnlManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnlManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnlManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnlManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlManagement;
    private javax.swing.JTable tblManagement;
    // End of variables declaration//GEN-END:variables
}
